### ISSUE TITLE
'BaseModel' object has no attribute 'to_static_state_dict'

### ISSUE THREAD

**Issue by SNeugber** [PaddlePaddle/Paddle2ONNX#601]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

I just upgraded from 0.9 to 0.9.1 and get the below error trace during export of my model.

**Informations (please complete the following information):**
 - Inference engine for deployment:
   - paddlepaddle_gpu-2.1.2.post112-cp39-cp39-linux_x86_64.whl
   - onnx==1.9.0
   - onnxruntime-gpu==1.10.0
 - Why convert to onnx: for inference
 - Paddle2ONNX Version: 0.9.1
 - Email/Wechat/Phone: 

**Screenshots**

```
   paddle.onnx.export(
    │      │    └ <function export at 0x7ff6fce4d700>
    │      └ <module 'paddle.onnx' from '/usr/local/lib/python3.9/dist-packages/paddle/onnx/__init__.py'>
    └ <module 'paddle' from '/usr/local/lib/python3.9/dist-packages/paddle/__init__.py'>

  File "/usr/local/lib/python3.9/dist-packages/paddle/onnx/export.py", line 100, in export
    p2o.dygraph2onnx(
    │   └ <function dygraph2onnx at 0x7ff56c6d0ca0>
    └ <module 'paddle2onnx' from '/usr/local/lib/python3.9/dist-packages/paddle2onnx/__init__.py'>

  File "/usr/local/lib/python3.9/dist-packages/paddle2onnx/convert.py", line 167, in dygraph2onnx
    paddle_graph = PaddleGraph.build_from_dygraph(layer, inner_input_spec,
                   │           │                  │      └ None
                   │           │                  └ BaseModel(
                   │           │                      (backbone): ResNet(
                   │           │                        (conv1_1): ConvBNLayer(
                   │           │                          (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding=...
                   │           └ <staticmethod object at 0x7ff56c71bf10>
                   └ <class 'paddle2onnx.graph.paddle_graph.PaddleGraph'>

  File "/usr/local/lib/python3.9/dist-packages/paddle2onnx/graph/paddle_graph.py", line 271, in build_from_dygraph
    program, feed_var_names, fetch_vars = dg_helper.get_program(
                                          │         └ <function get_program at 0x7ff56c6ef0d0>
                                          └ <module 'paddle2onnx.graph.dygraph_helper' from '/usr/local/lib/python3.9/dist-packages/paddle2onnx/graph/dygraph_helper.py'>

  File "/usr/local/lib/python3.9/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           │      │       │        │        └ {}
           │      │       │        └ (BaseModel(
           │      │       │            (backbone): ResNet(
           │      │       │              (conv1_1): ConvBNLayer(
           │      │       │                (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding...
           │      │       └ ()
           │      └ <function get_program at 0x7ff56c6ef040>
           └ <function wrap_decorator.<locals>.__impl__ at 0x7ff70a2f5940>

  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
           │             │       └ {}
           │             └ (BaseModel(
           │                 (backbone): ResNet(
           │                   (conv1_1): ConvBNLayer(
           │                     (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding...
           └ <function _switch_to_static_graph_.<locals>.__impl__ at 0x7ff58a4f3ee0>

  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (BaseModel(
           │         (backbone): ResNet(
           │           (conv1_1): ConvBNLayer(
           │             (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding...
           └ <function get_program at 0x7ff56c6ef040>

  File "/usr/local/lib/python3.9/dist-packages/paddle2onnx/graph/dygraph_helper.py", line 211, in get_program
    dygraph_state_dict = inner_layer.to_static_state_dict()
                         └ BaseModel(
                             (backbone): ResNet(
                               (conv1_1): ConvBNLayer(
                                 (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding=...

  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
                                   │     └ 'to_static_state_dict'
                                   └ BaseModel(
                                       (backbone): ResNet(
                                         (conv1_1): ConvBNLayer(
                                           (_pool2d_avg): AvgPool2D(kernel_size=1, stride=1, padding=...

AttributeError: 'BaseModel' object has no attribute 'to_static_state_dict'
```

**Additional context**

**Comment by yeliang2258** [comment]
Hello, will the Paddle2ONNX V.0.9.0 report this error ? 
You can use paddle.jit.save to save the inference model first, will you get the same error ?

**Comment by SNeugber** [comment]
> Hello, will the Paddle2ONNX V.0.9.0 report this error ?

I should have checked this before submitting the issue, sorry.
Everything works fine with 0.9.0, this issue only happens on 0.9.1.

**Comment by SNeugber** [comment]
>  You can use paddle.jit.save to save the inference model first, will you get the same error ?

This does indeed work with 0.9.1! :heavy_check_mark: 

```
output_path = "/tmp/my_model"
paddle.jit.save(model, output_path)
model = paddle.jit.load(output_path)
paddle.onnx.export(layer=model, path="/tmp/my_onnx_model", opset_version=11)
```
